docs: link to our config file for conventional commits warning (#10986)
If you mess this up and get the warning, it isn't very acitonable. I
then have to remember where to go look up the spec.
If you have suggestions on how else to make this more actionable,
let me know!

diff --git a/.github/workflows/pr-title.yml b/.github/workflows/pr-title.yml
--- a/.github/workflows/pr-title.yml
+++ b/.github/workflows/pr-title.yml
@@ -30,10 +30,15 @@ jobs:
         id: lint
         run: |
           failed=0
-          if ! npx commitlint --extends "@commitlint/config-conventional" --verbose <<< "$COMMIT_MSG"; then
-            failed=1
+          if ! lint_output=$(npx commitlint --extends "@commitlint/config-conventional" --verbose <<< "$COMMIT_MSG" 2>&1); then
+              failed=1
           fi
-          echo "failed=$failed" >> "$GITHUB_OUTPUT"
+          {
+              echo "failed=$failed"
+              echo "lint_output<<EOF"
+              echo "$lint_output"
+              echo "EOF"
+          } >> "$GITHUB_OUTPUT"
         env:
           COMMIT_MSG: |
             ${{ github.event.pull_request.title }}
@@ -61,6 +66,15 @@ jobs:
             The PR title and description are used as the merge commit message.
 
             Please update your PR title and description to match the specification.
+
+            See https://github.com/ibis-project/ibis/blob/main/.releaserc.js
+            for the list of acceptable prefixes, eg "feat:", "fix:", "chore:", etc.
+
+            The commitlint output is:
+
+            ```
+            ${{ steps.lint.outputs.lint_output }}
+            ```
 
       - name: fail the check if commitlint failed
         if: steps.lint.outputs.failed == '1'
